language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      sudo: required
      python: "3.6"
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - ${HOME}/.conan
          - ${TRAVIS_BUILD_DIR}/cmakebin
      after_success:
        - codecov -F Linux -X gcov
    - os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.6.5
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - $HOME/.pyenv
          - $HOME/Library/Caches/Homebrew
          - ${HOME}/.conan
      after_success:
        - codecov -F MacOS -X gcov
install:
  - source .CI/travis/install.sh
  - source .CI/travis/install_requirements.sh

script:
  - source .CI/travis/build_and_test.sh